### ISSUE TITLE
PowerNad 실행 오류 문의

### ISSUE THREAD

**Issue by ccwon77** [devkingsejong/python-PowerNad#1]
안녕하세요.
PowerNad를 설치하고, readme를 따라했는데 아래처럼 
"TypeError: 'module' object is not callable"라는 
오류 메시지가 나오는데 혹시 그 이유나 해결책을 알 수 있을까요?

![image](https://user-images.githubusercontent.com/16700486/35952641-542709ac-0cc4-11e8-8af2-bd1553ab5442.png)

**Comment by devkingsejong** [comment]
과제용으로 만든건데 관심 가져 주셔서 감사합니다..

해당부분
```
from powernad.API.AdGroup import *
```
와 같이 사용해 주셔야 합니다..
늦게 답변드려 죄송합니다.
