### ISSUE TITLE
안녕하세요. 에러관련 문의드립니다 (너무 잘 사용 중입니다 감사합니다)

### ISSUE THREAD

**Issue by Cheongah** [devkingsejong/python-PowerNad#10]
우선, 저는 개발자는 아니고 분석업무 위주로 수행하는 사람인데, 최근 외부 데이터 확보에 대한 과제가 많아서 크롤링 작업을 하게 되었습니다. (즉 왕초보 입니다..) 
네이버광고 - 키워드도구 - 결과데이터(조회수,클릭률등) 수집이 필요했는데 powernad 를 정말 유용하게 활용하고 있습니다. 감사합니다 (꾸벅)

powernad의 RelKwdStat 을 사용하여서 코드 작성 후 ,
1)구글코랩  2)VScode  두가지 환경에서 실행을 해봤는데요 . 
구글코랩에서는 결과가 잘 나오는 반면 똑같은 코드를 VScode에서 실행하면 [ 'NoneType' object is not subscriptable ] 에러가 납니다.  혹시 해결방안을 아실까요 ? 
(똑같은 코드인데 구글코랩에서 실행하면 잘 돌아가는데요.. 뭘까요 ? 혹시 환경변수 문제일까 PATH 에 Script 경로 추가된 것도 확인 했습니다 ㅜㅜ )

정말 감사합니다 !!

========= 파이썬 코드 =================
import os 
import io
import sys
import json
import jsonpickle
import urllib.request
from powernad.API.RelKwdStat import *
import sqlite3

API_CUSTOMER_ID = "API고객ID"
API_ACCESS_LICCENCE = "API라이센스키"
API_SECRET_KEY = "API시크릿키"
API_URL = "https://api.naver.com"

rel = RelKwdStat(API_URL, API_ACCESS_LICCENCE, API_SECRET_KEY, API_CUSTOMER_ID)

searchword="샴푸"

kwdDataList = rel.get_rel_kwd_stat_list(siteId=None, biztpId=None, hintKeywords=searchword, event=None, month=None, showDetail='1')

kwd_result = (kwdDataList[0].relKeyword,
          kwdDataList[0].monthlyPcQcCnt,
          kwdDataList[0].monthlyMobileQcCnt,
          kwdDataList[0].monthlyAvePcClkCnt,
          kwdDataList[0].monthlyAveMobileClkCnt,
          kwdDataList[0].monthlyAvePcCtr,
          kwdDataList[0].monthlyAveMobileCtr,
          kwdDataList[0].plAvgDepth,
          kwdDataList[0].compIdx
          )

print(kwd_result)

========= 에러메세지 =================
failed to request
Traceback (most recent call last):
  File "practice.py", line 26, in <module>
    kwdDataList = rel.get_rel_kwd_stat_list(siteId=None, biztpId=None, hintKeywords=searchword, event=None, month=None, showDetail='1')
  File "C:\Users\brightchung2\AppData\Local\Programs\Python\Python38\lib\site-packages\powernad\API\RelKwdStat.py", line 18, in get_rel_kwd_stat_list
    result = result['keywordList']
TypeError: 'NoneType' object is not subscriptable
PS D:\Cheongah\programming\python\crawling\Searchad>

**Comment by devkingsejong** [comment]
안녕하세요. 늦은 답변 죄송합니다.
혹 아직도 똑같은 에러이신가요?

키워드 관련 인코딩 문제가 아닐까 생각이 드는데요.
혹 `searchword="샴푸"` 를  `searchword="shoes"`(영어 단어)
로 테스트해보시겠어요?
