### ISSUE TITLE
확인하실지 모르겠네요...ㅠㅠ

### ISSUE THREAD

**Issue by simisae** [devkingsejong/python-PowerNad#12]
부디 확인해주셨으면...
파이썬 배운지 얼마 되지 않아 모르는 것이 많습니다.

get_stat_by_id

를 쓰려고 하는데,
네이버 가이드와 다른 점이 몇가지 있고, 안되는 것이 있어 말씀드립니다. ㅠㅠ
get_stat_by_id 의 파라미터를 보면, id, fields 는 꼭 기입해야하고,
timeRange 나 datePreset 은 둘 중 하나만 기입해도 작동한다고 하는데,
timeRange 를 정의하지 않으면 무조건 에러가 납니다.

또, datePreset 오타가 있는 것같네요.
네이버에선 datePreset 이라고 되어있는데 Stat.py 를 보니 dataPreset 이라고 되어있습니다.
date -> data 이렇게요. 뭐 오타는 크게 상관이 없지만,
이놈의 timeRange 형식을 대체 어떻게 써야할지 모르겠습니다.
네이버 예제로는
{"since":"YYYY-MM-DD","until":"YYYY-MM-DD"}
이렇게 되어있어서

st = statinfo.get_stat_by_id(id = 'nkw-a001-01-xxxxxxxxxxxxxx', fields = 'avgRnk', timeRange = {"since":"2020-05-25","until":"2020-05-26"})

이런식으로 해봤는데,
quote_from_bytes() expected bytes

이런 에러가 나구요,
말씀드렸다시피 timeRange 를 무조건 써야하기 때문에 datePreset 은 사용하나 마나구요. ㅠㅠ

어떻게 해결이 안될까요...?
매일 와서 답변 기다리겠습니다. ㅠㅠ

**Comment by devkingsejong** [comment]
곧 수정해 드리겠습니다. 잠시만 기다려 주세요.

**Comment by devkingsejong** [comment]
해당부분 수정하였습니다. DatePrest에 들어가는 값은

<img width="669" alt="스크린샷 2020-05-28 오후 1 08 41" src="https://user-images.githubusercontent.com/24914631/83098013-75f1f400-a0e4-11ea-83a3-314d5b2aedd8.png">

입니다.

**Comment by simisae** [comment]
아... 수정해주신 것 감사합니다.
그런데 또 여쭤봤던 것중에 하나가
timeRange 형식인데요...

timeRange 를 쓸 경우
st = statinfo.get_stat_by_id(id = 'nkw-a001-01-xxxxxxxxxxxxxx', fields = 'avgRnk', timeRange = {"since":"2020-05-25","until":"2020-05-26"})

이렇게 해봤는데 안됩니다.
어떤식으로 해야 이게 작동을 하는건지요...

그리고 위에도 말씀드렸듯이
timeRange 나 datePreset 은 둘 중 하나만 기입해도 작동한다고 하는데,
timeRange 를 정의하지 않으면 무조건 에러가 납니다.


정리하면,
1. timeRange 사용하는 방법
2. 네이버API 가이드에선 timeRange 나 datePreset 둘 중 하나만 써도  된다고 하는데 timeRange 가 강제됨

이렇게입니다. 답변 꼭 부탁드립니다. ㅠ

**Comment by devkingsejong** [comment]
```
fields = '["impCnt","clkCnt","salesAmt"]'
statr = stat.get_stat_by_id('grp-a001-01-000000002412336',
                                            fields, '{"since":"2017-02-26",
                                                         "until":"2017-03-04"}',
                                            None, None, None)
print(statr.data[0].dateEnd)
```

이렇게 사용하시면 됩니다.

**Comment by simisae** [comment]
답변 정말 감사드립니다. 좋은 하루 되세요! ^^

**Comment by devkingsejong** [comment]
나머지 사용법들도 대강적 내용들은
https://github.com/devkingsejong/python-PowerNad/blob/master/powernad/mini_api_doc.md

위 문서에 있습니다.

API 문서 없는점 죄송합니다.
관심 가져 주셔서 감사합니다.
