### ISSUE TITLE
안녕하세요.. 안되가지고 질문올립니다..

### ISSUE THREAD

**Issue by sunpunggi** [devkingsejong/python-PowerNad#6]
안녕하세요 파이썬 배우고 있는 초보 꿈나무 입니다.
다름이 아니라 키워드와 연관된 키워드를 뽑아보려고 하는데 잘 안되서요..
![11](https://user-images.githubusercontent.com/52964440/61296782-cbe3e300-a815-11e9-9e94-35e6346bd960.JPG)
![22](https://user-images.githubusercontent.com/52964440/61296783-cbe3e300-a815-11e9-925c-51660ee54ed9.JPG)

현재 이런 상황인데.. 도대체 왜 실행조차 안되는걸까요?
제 생각엔 import 경로도 맞는거 같은데..

답변좀 꼭좀 부탁드립니다..

**Comment by devkingsejong** [comment]
https://github.com/devkingsejong/python-PowerNad/blob/master/requirements.txt#L1

죄송합니다. 의존성이 제대로 설치되지 않은 것 같습니다.

```
pip install jsonpickle
```
을 해보셔도 안되면 다시 연락주세요.

**Comment by devkingsejong** [comment]
더불어.. api doc이 없는 관계로...

https://github.com/devkingsejong/python-PowerNad/blob/master/powernad/mini_api_doc.md

대략적으로 적혀있는 부분이 있긴 합니다..

**Comment by sunpunggi** [comment]
> 더불어.. api doc이 없는 관계로...
> 
> https://github.com/devkingsejong/python-PowerNad/blob/master/powernad/mini_api_doc.md
> 
> 대략적으로 적혀있는 부분이 있긴 합니다..


안녕하세요 의존성 설치를 하니 실행이 됐습니다. 감사합니다!
지금 키워드를 입력하면 조회수에 대한 정보를 받아보려고 하거든요..
그 기능이 RelKwdStat 클래스에 있는게 맞는건가요?
네이버 api에서는 RelKwdStat 클래스에서 키워드와 연관 키워드 조회를 할 수 있었던 것 같은데..
선생님께서 만드신 클래스 파일에는 없는 것 같아서요.. 답변 부탁드립니다.

**Comment by devkingsejong** [comment]
```
GetExposureMiniBidObjectex = GetExposureMiniBidObject('PC', 'DAY', ['화분', '보험'])
```
ExposureMiniObject를 get_exposure_mini_bid_list의 파라미터로 넣어주시면 됩니다.

https://github.com/devkingsejong/python-PowerNad/blob/master/powernad/API/Estimate.py#L58
와 같이 사용하시면 됩니다.
